version: "3"

services:
  kutt:
    image: kutt/kutt
    depends_on:
      - redis
    command: ["./wait-for-it.sh", "clggkg1al003vq1a4ezc53dko:5432", "--", "npm", "start"]
    ports:
      - "3001:3000"

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data:
